name: facebook_app_events_example
description: Demonstrates how to use the facebook_app_events plugin.
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  facebook_app_events:
    path: ../

flutter:
  uses-material-design: true
